# Generated by Django 4.0.5 on 2022-06-05 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instagram', '0002_alter_image_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='post_date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
