# Generated by Django 4.0.5 on 2022-06-06 14:21

from django.db import migrations, models
import instagram.models


class Migration(migrations.Migration):

    dependencies = [
        ('instagram', '0005_rename_profile_image_user_image_likes_stream_follow'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='pic',
            field=models.ImageField(blank=True, null=True, upload_to=instagram.models.user_directory_path),
        ),
    ]
